[package]
name = "nu_plugin_ndocker"
version = "0.1.0"
edition = "2024"

[dependencies]
bollard = "0.19.1"
chrono = "0.4.41"
nu-plugin = "0.105.1"
nu-protocol = "0.105.1"
nu-utils = "0.105.1"
serde = "1.0.219"
tokio = { version = "1.46.1", features = ["rt", "rt-multi-thread"] }
typetag = "0.2.20"
